name: Build Windows MSI

on:
  push:
    branches: [main]

jobs:
  build-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn package

      - name: Package with jpackage
        run: |
          mkdir output
          jpackage ^
            --type msi ^
            --input target ^
            --name ToDoApp ^
            --main-jar todo-app-1.0.0.jar ^
            --main-class com.example.todo.Main ^
            --java-options "--enable-preview" ^
            --win-dir-chooser ^
            --win-shortcut ^
            --win-menu ^
            --dest output ^
            --app-version 1.0

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v3
        with:
          name: ToDoAppInstaller
          path: output/*.msi